#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ft=python ts=4 sw=4 sts=4 et fenc=utf-8
# Original author: "Eivind Magnus Hvidevold" <hvidevold@gmail.com>
# License: GNU GPLv3 at http://www.gnu.org/licenses/gpl.html

'''
'''

import os
import sys
import re

def main():
    'entry point'
    ptypes = ['float', 'vec2', 'vec3', 'vec4', 'mat2', 'mat3', 'mat4']
    vartypes = ['fun', 'attr', 'varying', 'builtin', 'uniform', 'var', 'output', 'arg']

    print '/* Begin auto-generated by GLSLFunGen.py */'
    for ptype in ptypes:
        for vartype in vartypes:
            print 'let %s%s = name => Typed(`%s, RVar((%s, %s, name)));' % (ptype, vartype, ptype.title(), vartype.title(), ptype.title())
    print '/* End auto-generated by GLSLFunGen.py */'

if __name__ == '__main__':
    main()
